title Diagrama de Estado - Huesped@startuml DE-Huespedhide empty description[*] --> Creado : El huésped no existe[*] --> Registrado : El huésped está registradoCreado --> Validado : Se validan los datos del altaCreado --> Creado : Los datos no son validosValidado --> Registrado : El huésped se registra en el sistemaRegistrado --> Alojado : El huésped está en el hotelAlojado --> [*] : Check-outRegistrado --> [*] : El huesped no tiene reserva o la cancela@enduml