title Diagrama de Estado - Huesped@startuml DE-Huespedhide empty description[*] --> Creado : El huésped no existe[*] --> Registrado : El huésped está registradoCreado --> Validado : Se validan los datos del altaValidado --> Registrado : El huésped se registra en el sistemaRegistrado --> Alojado : El huésped está en el hotelAlojado --> [*] : Check-outRegistrado --> [*] : Se guarda el huésped en la BD@enduml